server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /albarq-staff-debug.apk {
    default_type application/vnd.android.package-archive;
    add_header Content-Disposition 'attachment; filename="albarq-staff-debug.apk"';
    try_files /albarq-staff-debug.apk =404;
  }

  location /api/ {
    proxy_pass http://backend:4000/api/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
