import { Request, Response } from 'express';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CHAP_PATH = process.env.CHAP_SECRETS_PATH || '/etc/ppp/chap-secrets';
const XL2TPD_SERVICE = process.env.XL2TPD_SERVICE || 'xl2tpd';
const STRONGSWAN_SERVICE = process.env.STRONGSWAN_SERVICE || 'strongswan';

function getActorId(req: Request) {
  return (req as any).user?.id || null;
}

function normalize(row: any, online = new Map<string, any>()) {
  const state = online.get(String(row.username));
  return {
    id: row.id,
    username: row.username,
    password: row.password,
    service: row.service,
    remote_ip: row.remoteIp || '',
    local_ip: row.localIp || '',
    routed_ranges: row.routedRanges || '',
    expires_at: row.expiresAt,
    enabled: row.enabled,
    online: Boolean(state?.online),
    last_login: state?.last_login || null,
    notes: row.notes || '',
    created_at: row.createdAt,
    updated_at: row.updatedAt,
  };
}

function readOnlineVpnUsers() {
  const online = new Map<string, { online: boolean; last_login?: string; local_ip?: string; remote_ip?: string }>();

  try {
    const ppp = execSync("ip -o addr show | grep -E ' ppp[0-9]+' || true", {
      encoding: 'utf8',
      timeout: 2000,
    });

    const logs = execSync("journalctl -u xl2tpd --no-pager -n 600 2>/dev/null || true", {
      encoding: 'utf8',
      timeout: 3500,
    });

    const currentIps = new Set<string>();
    for (const line of ppp.split('\n')) {
      const m = line.match(/\s(ppp\d+)\s+inet\s+(\S+)\s+peer\s+(\S+)/);
      if (m) currentIps.add(m[3].split('/')[0]);
    }

    let lastUser = '';
    for (const line of logs.split('\n')) {
      const userMatch = line.match(/name\s*=\s*"([^"]+)"/i) || line.match(/CHAP.*"([^"]+)"/i);
      if (userMatch) lastUser = userMatch[1];

      const ipMatch = line.match(/remote IP address\s+([0-9.]+)/i);
      if (ipMatch && lastUser) {
        online.set(lastUser, {
          online: currentIps.has(ipMatch[1]) || true,
          last_login: line.trim(),
          remote_ip: ipMatch[1],
        });
      }

      if (/terminated|disconnect|closed|hangup/i.test(line) && lastUser && online.has(lastUser)) {
        const old = online.get(lastUser);
        online.set(lastUser, { ...old, online: false, last_login: line.trim() });
      }
    }
  } catch {}

  return online;
}

async function log(vpnUserId: string | null, actorId: string | null, action: string, description?: string) {
  await prisma.vpnLog.create({
    data: {
      vpnUserId,
      actorId,
      action,
      description,
    },
  });
}

async function generateChapSecrets(actorId?: string | null) {
  const users = await prisma.vpnUser.findMany({
    where: { enabled: true, service: 'l2tp' },
    orderBy: { username: 'asc' },
  });

  const lines = users.map((u) => {
    const remote = u.remoteIp?.trim() || '*';
    return `${u.username}\tAlbarqVPN\t${u.password}\t${remote}`;
  });

  const content = [
    '# Generated by Call Center Albarq',
    `# ${new Date().toISOString()}`,
    ...lines,
    '',
  ].join('\n');

  if (fs.existsSync(CHAP_PATH)) {
    fs.copyFileSync(CHAP_PATH, `${CHAP_PATH}.bak.${Date.now()}`);
  }

  fs.writeFileSync(CHAP_PATH, content, { mode: 0o600 });
  await log(null, actorId || null, 'generate_chap', CHAP_PATH);

  return { path: CHAP_PATH, users: users.length };
}

export async function list(req: Request, res: Response) {
  const q = String(req.query.q || '').trim();

  const where = q
    ? {
        OR: [
          { username: { contains: q } },
          { remoteIp: { contains: q } },
          { localIp: { contains: q } },
          { notes: { contains: q } },
        ],
      }
    : {};

  const rows = await prisma.vpnUser.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: 500,
  });

  const online = readOnlineVpnUsers();
  res.json(rows.map((r) => normalize(r, online)));
}

export async function create(req: Request, res: Response) {
  const username = String(req.body.username || '').trim();
  const password = String(req.body.password || '').trim();

  if (!username || !password) {
    return res.status(400).json({ error: 'Username and password are required' });
  }

  const row = await prisma.vpnUser.create({
    data: {
      username,
      password,
      service: req.body.service || 'l2tp',
      remoteIp: req.body.remote_ip || req.body.remoteIp || null,
      localIp: req.body.local_ip || req.body.localIp || null,
      routedRanges: req.body.routed_ranges || req.body.routedRanges || null,
      expiresAt: req.body.expires_at ? new Date(req.body.expires_at) : null,
      enabled: req.body.enabled === false ? false : true,
      notes: req.body.notes || null,
      createdBy: getActorId(req),
    },
  });

  await log(row.id, getActorId(req), 'create', `Created VPN user ${username}`);
  await generateChapSecrets(getActorId(req));
  res.status(201).json(normalize(row));
}

export async function update(req: Request, res: Response) {
  const id = req.params.id;

  const old = await prisma.vpnUser.findUnique({ where: { id } });
  if (!old) return res.status(404).json({ error: 'VPN user not found' });

  const row = await prisma.vpnUser.update({
    where: { id },
    data: {
      username: req.body.username ?? undefined,
      password: req.body.password ?? undefined,
      service: req.body.service ?? undefined,
      remoteIp: req.body.remote_ip ?? req.body.remoteIp ?? null,
      localIp: req.body.local_ip ?? req.body.localIp ?? null,
      routedRanges: req.body.routed_ranges ?? req.body.routedRanges ?? null,
      expiresAt: req.body.expires_at ? new Date(req.body.expires_at) : null,
      enabled: req.body.enabled === undefined ? undefined : Boolean(req.body.enabled),
      notes: req.body.notes ?? null,
    },
  });

  await log(id, getActorId(req), 'update', `Updated VPN user ${row.username}`);
  await generateChapSecrets(getActorId(req));
  res.json(normalize(row));
}

export async function toggle(req: Request, res: Response) {
  const id = req.params.id;
  const old = await prisma.vpnUser.findUnique({ where: { id } });
  if (!old) return res.status(404).json({ error: 'VPN user not found' });

  const row = await prisma.vpnUser.update({
    where: { id },
    data: { enabled: !old.enabled },
  });

  await log(id, getActorId(req), 'toggle', `enabled=${row.enabled}`);
  await generateChapSecrets(getActorId(req));
  res.json(normalize(row));
}

export async function extend(req: Request, res: Response) {
  const id = req.params.id;
  const months = Math.max(1, Number(req.body.months || 1));

  const old = await prisma.vpnUser.findUnique({ where: { id } });
  if (!old) return res.status(404).json({ error: 'VPN user not found' });

  const base = old.expiresAt && old.expiresAt > new Date() ? old.expiresAt : new Date();
  const next = new Date(base);
  next.setMonth(next.getMonth() + months);

  const row = await prisma.vpnUser.update({
    where: { id },
    data: { expiresAt: next },
  });

  await log(id, getActorId(req), 'extend', `Extended ${months} month(s)`);
  await generateChapSecrets(getActorId(req));
  res.json(normalize(row));
}

export async function remove(req: Request, res: Response) {
  const id = req.params.id;
  const old = await prisma.vpnUser.findUnique({ where: { id } });
  if (!old) return res.status(404).json({ error: 'VPN user not found' });

  await prisma.vpnUser.delete({ where: { id } });
  await log(null, getActorId(req), 'delete', `Deleted VPN user ${old.username}`);
  await generateChapSecrets(getActorId(req));
  res.json({ ok: true });
}

export async function generateChap(req: Request, res: Response) {
  const result = await generateChapSecrets(getActorId(req));
  res.json({ ok: true, ...result });
}

export async function restartService(req: Request, res: Response) {
  execSync(`systemctl restart ${XL2TPD_SERVICE}`, { timeout: 10000 });

  try {
    execSync(`systemctl restart ${STRONGSWAN_SERVICE}`, { timeout: 12000 });
  } catch {}

  await log(null, getActorId(req), 'restart_service', `restart ${XL2TPD_SERVICE}/${STRONGSWAN_SERVICE}`);
  res.json({ ok: true });
}

export async function applyRoutes(req: Request, res: Response) {
  const id = req.params.id;

  const user = await prisma.vpnUser.findUnique({ where: { id } });
  if (!user) return res.status(404).json({ error: 'VPN user not found' });

  const gateway = String(user.remoteIp || '').trim();
  if (!gateway || gateway === '*') {
    return res.status(400).json({ error: 'Set a real Remote IP first, e.g. 10.50.50.10' });
  }

  const ranges = String(user.routedRanges || '')
    .split(/[\n,]+/)
    .map((x) => x.trim())
    .filter(Boolean);

  if (!ranges.length) return res.status(400).json({ error: 'No routed ranges provided' });

  for (const cidr of ranges) {
    if (!/^(?:\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/.test(cidr)) {
      return res.status(400).json({ error: `Invalid CIDR: ${cidr}` });
    }
  }

  const safeGateway = gateway.replace(/\./g, '\\.');
  const dev = execSync(`ip -o addr show | awk '/peer ${safeGateway}/ {print $2; exit}'`, {
    encoding: 'utf8',
    timeout: 2500,
  }).trim() || 'ppp0';

  for (const cidr of ranges) {
    execSync(`ip route replace ${cidr} via ${gateway} dev ${dev}`, { timeout: 3000 });
  }

  await log(id, getActorId(req), 'apply_routes', `${ranges.join(', ')} via ${gateway} dev ${dev}`);
  res.json({ ok: true, gateway, dev, routes: ranges });
}

export async function logs(_req: Request, res: Response) {
  const rows = await prisma.vpnLog.findMany({
    orderBy: { createdAt: 'desc' },
    take: 300,
  });
  res.json(rows);
}

export async function status(_req: Request, res: Response) {
  const out = execSync("/opt/scripts/vpn-status.sh || true", {
    encoding: 'utf8',
    timeout: 3000,
  });

  const [ipPart = '', routePart = ''] = out.split('=== ROUTES ===');
  res.json({
    ip: ipPart.replace('=== IP ===', '').trim(),
    routes: routePart.trim(),
  });
}
